config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check
  resources :cars
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  resources :garages
  get "my_garage", to: "garages#my_garage"
  # Defines the root path route ("/")
  # root "posts#index"


  resources :cars do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show, :edit, :update, :destroy]

  get "my_bookings", to: "bookings#my_bookings"

  resources :garages do
    resources :cars, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :cars, only: [:index, :show]

  resources :bookings, only: [:create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :start_date, presence: true
  validates :finish_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :garage
  has_one_attached :image

  validates :model, presence: true
  validates :year, presence: true
  validates :brand, presence: true
  validates :color, presence: true
  validates :capacity, presence: true
  validates :price, presence: true
end

app/models/garage.rb
class Garage < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  has_many :cars, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :garages
  has_many :bookings

  validates :phone, presence: true
  validates :address, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone, :address])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_car, only: %i[new create]
  
  def new
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
    @car = @booking.car
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.car = @car
    if @booking.save
      redirect_to my_bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to my_bookings_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to my_bookings_path, status: :see_other
  end

  def my_bookings
    @my_bookings = Booking.where(user: current_user)
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :finish_date, :car_id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to car_path(@car), notice: "You have register a new car"
    else
      render :new, alert: "We have a problem to register your car"
    end
  end

  def show
    @car = Car.find(params[:id])
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
      if @car.update(car_params)
        redirect_to cars_path
      else
        render :edit
      end
  end

  def destroy
    @car = Car.find(params[:id])
      if @car.destroy
        redirect_to cars_path
      end
  end

  private

  def car_params
    params.require(:car).permit(:brand, :color, :year, :price, :model, :capacity, :garage_id, :image)
  end
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
  def index
    @garages = Garage.all
  end

  def new
    @garage = Garage.new
  end

  def create
    @garage = Garage.new(garage_params)
    @garage.user = current_user
    if @garage.save!
      redirect_to my_garage_path
    else
      render :new
    end
  end

  def show
    @garage = Garage.find(params[:id])
  end

  def edit
    @garage = Garage.find(params[:id])
  end

  def update
    @garage = Garage.find(params[:id])
      if @garage.update(garage_params)
        redirect_to garages_path
      else
        render :edit
      end
  end

  def destroy
    @garage = Garage.find(params[:id])
      if @garage.destroy
        redirect_to my_garage_path, notice: "Garage eliminado exitosamente."
      end
  end

  def my_garage
    @garage = Garage.where(user: current_user)
  end

  private

  def garage_params
    params.require(:garage).permit(:name, :address, :user_id, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
<%= simple_form_for [car, booking] do |f| %>
<div class="row d-flex align-items-center justify-content-center g-3 bg-light">
  <div class="col-md-4 mt-1">
    <%= f.input :start_date,
               as: :string,
            input_html: { data: { controller: "datepicker" } } , required:false%>
  </div>

  <div class="col-md-4 mt-1">
    <%= f.input :finish_date,
              as: :string,
            input_html: { data: { controller: "datepicker" } } , required:false%>
  </div>

  <div class="col-md-4">
    <%= f.submit "Start Booking", class: "btn btn-primary w-100" %>
  </div>

</div>
<% end %>
</div>

app/views/bookings/edit.html.erb
<div class="content-with-navbar-spacing">
  <div class="mybanner" style="background-image: url('https://cdn.www.gob.pe/uploads/document/file/1536765/WhatsApp%20Image%202021-01-08%20at%2009.50.54.jpeg.jpeg');">
      <div class="containerbanner1">
        <h1>Edit your reservation</h1>
      </div>

    </div>
    <div class="form-rent2">
          <%= render "form", booking: @booking, car: @car %>
          <p>Are you sure you want to change the date?</p>
    </div>
  </div>
</div>

app/views/bookings/my_bookings.html.erb
<div class="content-with-navbar-spacing">
    <table class="table table-striped">
     <thead>
       <tr>
         <th scope="col">Brand</th>
         <th scope="col">Start</th>
         <th scope="col">Finish</th>
         <th scope="col">Actions</th>
       </tr>
     </thead>
     <tbody>
     <% @my_bookings.each do |booking|  %>
       <tr>
         <td><%= booking.car.brand %></td>
         <td><%= booking.start_date %></td>
         <td><%= booking.finish_date %></td>
         <td><%= link_to "Edit", edit_booking_path(booking), class: "btn btn-secondary btn-sm" %> | <%= link_to "Delete", booking_path(booking), class: "btn btn-danger btn-sm", data: {turbo_method: :delete} %></td>
       </tr>
     <% end %>
    </tbody>
  |</table>
</div>

app/views/bookings/new.html.erb
<div class="content-with-navbar-spacing">
  <div class="mycontainer">
      <p class="mytext"><strong>Your Selection:</strong> </p>
    <div class="mycards">
      <div class="mycard">
        <h3 class="card-title mb-4"><strong><%= @car.brand %> <%= @car.model %></strong></h3>
      </div>
      <div class="mycard">
        <img src="https://www.budgetperu.com/files/mid-veh3.jpg" alt="Le Wagon logo" >
        <%#= image_tag @car.image %>
      </div>
    </div>
  </div>

  <div class="mybanner" style="background-image: url('https://cdn.www.gob.pe/uploads/document/file/1536765/WhatsApp%20Image%202021-01-08%20at%2009.50.54.jpeg.jpeg');">
    <div class="containerbanner">
      <h1>Book your reservation online</h1>
      <div>
        <h5 class="text-white" id="cambiarTexto">Obtain the best rate rigth away</h5>
        <script>
          const textos = ["Obtain the best rate rigth away", "Discover hot deals and free perks", "Fast and 100% secure"];
          let indice = 0;
          setInterval(() => {
            indice = (indice + 1) % textos.length;
            document.getElementById("cambiarTexto").textContent = textos[indice];
          }, 2000);
         </script>
      </div>
    </div>

  </div>
  <div class="form-rent">
        <%= render "form", booking: @booking, car: @car %>
        <p>First time renting a car?</p>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container mt-4">
  <h2>Detalles de la Reserva</h2>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Reserva #<%= @booking.id %></h5>

      <p class="card-text">
        <strong>Fecha de Inicio:</strong> <%= @booking.start_date %>
      </p>

      <p class="card-text">
        <strong>Fecha de Fin:</strong> <%= @booking.finish_date %>
      </p>

      <p class="card-text">
        <strong>Auto:</strong> <%= @booking.car.brand %> <%= @booking.car.model %>
      </p>

      <div class="mt-3">
        <%= link_to "Modificar",
            edit_car_booking_path(@booking.car, @booking),
            class: "btn btn-primary" %>

        <%= link_to "Volver al Auto",
            car_path(@booking.car),
            class: "btn btn-secondary" %>

        <%= link_to "Eliminar",
            booking_path(@booking),
            data: { turbo_method: :delete, turbo_confirm: "¿Estás seguro?" },
            class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/cars/edit.html.erb
<%= simple_form_for(@car) do |c| %>
  <%= c.input :brand%>
  <%= c.input :model%>
  <%= c.input :year%>
  <%= c.input :price%>
  <%= c.input  :capacity%>
  <%= c.input  :color%>
  <%= c.association :garage, collection: current_user.garages, prompt: "Choose a garage"  %>
  <%= c.submit %>
  <%end%>

app/views/cars/index.html.erb
<div class="content-with-navbar-spacing">
  <div class="container">
    <div class="row">
      <% @cars.each do |car| %>
        <div class="col-md-4 mb-4">
          <div class="card h-100 shadow-sm border-0 hover-zoom">
            <% if car.image.attached? %>
              <%= image_tag url_for(car.image), alt: car.model, class: "card-img-top img-fluid fixed-image" %>
            <% else %>
              <img src="placeholder.jpg" class="card-img-top img-fluid fixed-image" alt="No photo available">
            <% end %>
            <div class="card-body text-center">
              <h5 class="card-title"><%= car.model %></h5>
              <p class="text-muted"><strong>Precio:</strong> $<%= car.price %>/día</p>
              <div class="d-flex justify-content-around">

                <% if current_user && car.garage && current_user.id != car.garage.user_id %>
                  <%= link_to "Rentar", new_car_booking_path(car), class: "btn btn-outline-primary btn-sm" %>
                <% end %>

                <%= link_to "Ver más", car_path(car), class: "btn btn-secondary btn-sm" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="content-with-navbar-spacing">
  <%= simple_form_for(@car) do |c| %>
    <%= c.input :brand%>
    <%= c.input :model%>
    <%= c.input :year%>
    <%= c.input :price%>
    <%= c.input :capacity%>
    <%= c.input :color%>
    <%= c.input :extras%>
    <%= c.input :image%>
    <%=  c.association :garage, collection: current_user.garages, prompt: "Choose a garage" %>
    <%=c.submit %>
  <%end%>
</div>

app/views/cars/show.html.erb
<div class="content-with-navbar-spacing">
  <div class="d-flex justify-content-center">
    <div class="col-md-8 col-lg-6">
      <div class="card shadow-lg">
        <% if @car.image.attached? %>
          <%= image_tag url_for(@car.image), alt: @car.model, class: "card-img-top img-fluid fixed-image hover-zoom" %>
        <% else %>
          <img src="placeholder.jpg" class="card-img-top img-fluid fixed-image hover-zoom" alt="No photo available">
        <% end %>

        <div class="card-body text-center">
          <h2 class="card-title mb-3"><%= @car.model %> - <%= @car.year %></h2>
        </div>

        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>Marca: </strong><%= @car.brand %></li>
          <li class="list-group-item"><strong>Capacidad: </strong><%= @car.capacity %> asientos</li>
          <li class="list-group-item"><strong>Color: </strong><%= @car.color %></li>
          <li class="list-group-item"><strong>Precio: </strong>$<%= @car.price %>/día</li>
        </ul>

        <div class="card-body d-flex justify-content-around">
          <%= link_to "Ver más modelos", cars_path, class: "btn btn-secondary btn-sm" %>
          <% if current_user && @car.garage && current_user.id != @car.garage.user_id %>
            <%= link_to "Reservar este auto", new_car_booking_path(@car), class: "btn btn-primary btn-sm" %>
          <% end %>

          <% if current_user && @car.garage && current_user.id == @car.garage.user_id %>
            <%= link_to "Editar", edit_car_path(@car), class: "btn btn-warning btn-sm" %>
            <%= link_to "Eliminar", car_path(@car), class: "btn btn-danger btn-sm", data: { turbo_method: :delete, turbo_confirm: "¿Estás seguro?" } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/garages/edit.html.erb
<div class="content-with-navbar-spacing">
  <%= simple_form_for(@garage) do |g| %>
    <%= g.input :name%>
    <%= g.input :address%>
    <%=g.submit %>
  <%end%>

  <%= link_to "Regresar", my_garage_path, class: "btn btn-secondary" %>
</div>

app/views/garages/index.html.erb
<div class="content-with-navbar-spacing">
  <h1><strong>Available garages</strong></h1>
  <div class="container">
    <div class="row">
      <%@garages.each do |c|%>
        <div class="card m-3" style="width: 18rem;">
          <!--img src="..." class="card-img-top" alt="...">-->
          <div class="card-body">
            <h5 class="card-title"><strong>Name: </strong><%=c.name%></h5>
            <p class="card-text"><strong>Address: </strong><%=c.address%></p>
            <%= link_to "Ver Garage", garage_path(c), class: "btn btn-primary" %>
          </div>
        </div>
      <%end%>
    </div>
  </div>

  <%= link_to "Ver modelos disponibles", cars_path, class: "btn btn-secondary" %>
</div>

app/views/garages/my_garage.html.erb
<div class="content-with-navbar-spacing">
  <h1>My Garages</h1>

  <div class="mb-4">
    <%= link_to "Crear Garage", new_garage_path, class: "btn btn-primary" %>
  </div>

  <% @garage.each do |g| %>
    <div class="card mb-4" style="width: 18rem;">
      <% if g.image.attached? %>
        <%= image_tag url_for(g.image), alt: g.name, class: "card-img-top img-fluid" %>
      <% else %>
        <img src="placeholder.jpg" alt="No photo available" class="card-img-top img-fluid">
      <% end %>

      <div class="card-body">
        <h3><%= g.name %></h3>
        <p><%= g.address %></p>
      </div>

      <div class="card-body d-flex justify-content-between gap-1">
        <%= link_to "Edit", edit_garage_path(g), class: "btn btn-warning btn-sm" %>
        <%= link_to "Delete", garage_path(g), class: "btn btn-danger btn-sm", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      </div>

      <!-- Botón para registrar un auto en este garage -->
      <div class="card-footer text-center">
        <%= link_to "Registrar Auto", new_garage_car_path(g), class: "btn btn-outline-primary btn-sm" %>
      </div>
    </div>
  <% end %>
</div>

app/views/garages/new.html.erb
<div class="content-with-navbar-spacing">
  <h1>Create a new garage! 🚘</h1>
  <%= simple_form_for(@garage) do |g| %>
    <%= g.input :name%>
    <%= g.input :address%>
    <%= g.input :image, as: :file, label: "Foto de portada" %>
    <%= g.submit "Registrar Garage", class: "btn btn-primary" %>
  <%end%>

   <div class="mt-3">
    <%= link_to "Regresar", my_garage_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/garages/show.html.erb
<div class="content-with-navbar-spacing">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h3> <strong>Your Garage</strong></h3>
      <h5 class="card-title"><%=@garage.address%></h5>
      <p class="card-text"><%=@garage.name %></p>
    </div>

    <div class="card-body d-flex justify-content-between gap-1">
      <%= link_to "Edit", edit_garage_path(@garage), class: "btn btn-warning btn-sm" %>
      <%= link_to "Delete", garage_path(@garage), class: "btn btn-danger btn-sm", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </div>

    <%= link_to "Register your car", new_garage_car_path(@garage), class: "btn btn-primary btn-block" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Open Garage" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <div class="container">
      <%= render "shared/navbar"  %>
      <%= render "shared/flashes" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="content-with-navbar-spacing">
<div class="banner">
  <img id="banner" src="https://wallpapers.com/images/hd/ultra-wide-4k-car-3lxbiug6ognbvkxm.jpg" alt="Car">
</div>
<div class="slogan">
  <h1> <strong>Rent faster cars, in a faster way!</strong></h1>
  <h4>Go wherever you want! there's a car waiting for you</h4>
</div>
<div class="row d-flex justify-content-center">
  <div class="col-6">
    <div class="explore d-flex justify-content-center">
      <div class="card mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="https://img.freepik.com/premium-photo/vertical-view-fronts-many-cars-parked-parking-lot_646632-5853.jpg" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><strong>Every car, for every ocassion</strong></h5>
            <p class="card-text"> See all of our cars, ranging from SUV'S to sport cars</p>
            <p class="card-text"><small class="text-body-secondary">Our premium selection</small></p>
            <%= link_to "See more!","/cars", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
  <div class="col-6">
    <div class="explored d-flex justify-content-center">
      <div class="card mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-4">
           <%= image_tag "garage.jpg", class: "img-fluid rounded-start" %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><strong>Passive income, the easy way!</strong></h5>
            <p class="card-text">Become a host and start making money today!</p>
            <p class="card-text"><small class="text-body-secondary"> create your journey </small></p>
          <%= link_to "Create your garage!","/garages/new", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>



 <!-- inicio del carrusel  -->
<div id="carouselExample" class="carousel slide">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://www.rutamotor.com/wp-content/uploads/2023/12/SUV-Rutamotor-1170x722.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://www.bmw.cl/content/dam/bmw/common/all-models/m-series/x6m/2023/highlights/bmw-m-series-x6-m-gallery-image-impressionen-03_1920.jpg.asset.1675123934752.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://audi.klassikcar.cl/wp-content/uploads/GALLERY-NUEVO-Q7-1920x1080_-1..jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" dat a-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/ds64mjyoj/image/upload/v1731140954/Key_car_xfcyel.jpg", alt: "Icono", class: "icon-class" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= link_to "Open garage", root_path, class: "position-absolute top-0 start-50 translate-middle-x h1 text-decoration-none text-dark" %>
  <ul class="navbar-nav me-auto">

  <div class="d-flex justify-content-end align-items-center">
    <% if user_signed_in? %>
      <p class="mb-0 me-3">Bienvenido, <%= current_user.first_name %></p>
      <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary btn-sm" %>
    <% else %>
      <%= link_to 'Iniciar sesión', new_user_session_path, class: "btn btn-primary btn-sm me-2" %>
      <%= link_to 'Registrarse', new_user_registration_path, class: "btn btn-secondary btn-sm" %>
    <% end %>
  </div>

    <li class="nav-item d-flex justify-content-end align-items-center">
      <%= link_to "Cars", cars_path, class: "nav-link" %>
    </li>
    <li class="nav-item dropdown">
      <%= image_tag "https://static.vecteezy.com/system/resources/previews/009/267/561/original/user-icon-design-free-png.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "My garage", my_garage_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
        </div>
    </li>
  </ul>
</div>